font_size 12
scrollback_lines 5000
scrollback_pager_history_size 10
remember_window_size yes
initial_window_width 1920 
initial_window_height 1080 

cursor_trail 200
cursor_trail_delay 0.1 0.4
cursor_trail_start_threshold 2


# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
