vim.cmd("set termguicolors")
vim.cmd("colorscheme cyberdream")
vim.cmd("set autoindent")
vim.cmd("set hidden")
vim.cmd("set number")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set autoindent")
print("initialised custom settings")
